// The sidebar, built from the repository's folders: one category per lab, titled by its INSTRUCTIONS.md heading,
// so that nothing inside labs/ exists only for the site.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

function title(file) {
  const heading = fs.readFileSync(path.join(ROOT, file), 'utf8').match(/^# (.+)$/m);
  return heading ? heading[1].trim() : file;
}

const labs = fs
  .readdirSync(path.join(ROOT, 'labs'), {withFileTypes: true})
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort()
  .map((lab) => ({
    type: 'category',
    label: title(`labs/${lab}/INSTRUCTIONS.md`),
    link: {type: 'doc', id: `labs/${lab}/INSTRUCTIONS`},
    items: [
      `labs/${lab}/checklist`,
      ...(fs.existsSync(path.join(ROOT, 'labs', lab, 'stories'))
        ? [{type: 'category', label: 'Stories', items: [{type: 'autogenerated', dirName: `labs/${lab}/stories`}]}]
        : []),
    ],
  }));

module.exports = {
  workshop: [
    'README',
    'SETUP',
    'GLOSSARY',
    {type: 'category', label: 'Labs', link: {type: 'doc', id: 'labs/README'}, items: labs},
    {
      type: 'category',
      label: 'Guides',
      items: ['docs/environments', 'docs/conventions'],
    },
    {
      type: 'category',
      label: 'Transcripts',
      link: {type: 'doc', id: 'transcripts/README'},
      items: [{type: 'autogenerated', dirName: 'transcripts'}],
    },
    {
      type: 'category',
      label: 'Facilitators',
      items: [{type: 'autogenerated', dirName: 'docs/facilitator'}, 'docs/WWWW_Workshop_Master_Preparation'],
    },
  ],
};
