// The sidebar, built from the repository's folders: one category per lab, titled by its INSTRUCTIONS.md heading,
// so that nothing inside labs/ exists only for the site.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// The transcripts and reference pages live on the solutions branch, never on main (spec: workshop/solutions).
for (const folder of ['transcripts', 'solutions']) {
  if (!fs.existsSync(path.join(ROOT, folder))) {
    throw new Error(`${folder}/ is missing: run \`npm run reference\` first, which adds it from the solutions branch.`);
  }
}

function title(file) {
  const heading = fs.readFileSync(path.join(ROOT, file), 'utf8').match(/^# (.+)$/m);
  return heading ? heading[1].trim() : file;
}

// The day's labs (lab-*) and the self-paced bonus labs (bonus-*), each a category of its own.
const labFolders = (prefix) =>
  fs
    .readdirSync(path.join(ROOT, 'labs'), {withFileTypes: true})
    .filter((entry) => entry.isDirectory() && entry.name.startsWith(prefix))
    .map((entry) => entry.name)
    .sort();

const labCategory = (lab) => ({
  type: 'category',
  label: title(`labs/${lab}/INSTRUCTIONS.md`),
  link: {type: 'doc', id: `labs/${lab}/INSTRUCTIONS`},
  items: [
    `labs/${lab}/checklist`,
    ...(fs.existsSync(path.join(ROOT, 'labs', lab, 'stories'))
      ? [{type: 'category', label: 'Stories', items: [{type: 'autogenerated', dirName: `labs/${lab}/stories`}]}]
      : []),
  ],
});

const labs = labFolders('lab-').map(labCategory);
const bonus = labFolders('bonus-').map(labCategory);

module.exports = {
  workshop: [
    'README',
    'SETUP',
    'GLOSSARY',
    {type: 'category', label: 'Labs', link: {type: 'doc', id: 'labs/README'}, items: labs},
    {type: 'category', label: 'Bonus', items: bonus},
    {
      type: 'category',
      label: 'Guides',
      items: ['docs/environments', 'docs/conventions', 'docs/robotcode', 'docs/building-with-agents'],
    },
    {
      type: 'category',
      label: 'Transcripts',
      link: {type: 'doc', id: 'transcripts/README'},
      items: [{type: 'autogenerated', dirName: 'transcripts'}],
    },
    {
      type: 'category',
      label: 'Solutions',
      link: {type: 'doc', id: 'solutions/README'},
      items: [{type: 'autogenerated', dirName: 'solutions'}],
    },
    {
      type: 'category',
      label: 'Facilitators',
      items: [{type: 'autogenerated', dirName: 'docs/facilitator'}, 'docs/WWWW_Workshop_Master_Preparation'],
    },
  ],
};
